export const READ_CHAR_CLASS = 'READ_CHAR_CLASS';
export const READ_CHAR_CLASS_LIST = 'READ_CHAR_CLASS_LIST';

export const CHAR_CLASS_LIST_READ = 'CHAR_CLASS_LIST_READ';
export const CHAR_CLASS_READ = 'CHAR_CLASS_READ';
