export const SEARCH_BOOK = 'SEARCH_BOOK';

export const SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS';
export const SEARCH_BOOK_FAILURE = 'SEARCH_BOOK_FAILURE';

export const CLEAR_SEARCH_BOOK = 'CLEAR_SEARCH_BOOK';
