export const SEARCH_BOOK = 'SEARCH_BOOK';

export const SET_BOOK_IDS = 'SET_BOOK_IDS';

export const SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS';
export const SEARCH_BOOK_FAILURE = 'SEARCH_BOOK_FAILURE';
